apiVersion: v1
kind: ConfigMap
metadata:
  name: basic-auth-plugin-config
  labels:
    app: basic-auth-plugin
  namespace: basic-auth-plugin
data:
  envoy.yaml: |
    static_resources:
      listeners:
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 10000
        filter_chains:
          - filters:
              - name: envoy.filters.network.http_connection_manager
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                  stat_prefix: ingress_http
                  codec_type: AUTO
                  route_config:
                    name: local_route
                    virtual_hosts:
                      - name: local_service
                        domains:
                          - "*"
                        routes:
                          - match:
                              prefix: "/"
                            route:
                              cluster: httpbin

                  http_filters:
                    - name: envoy.filters.http.wasm
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
                        config:
                          name: "basic-auth-plugin"
                          configuration:
                            "@type": "type.googleapis.com/google.protobuf.StringValue"
                            value: |
                              allowed_users:
                                - username: "test1"
                                  password: "password1"
                              cookie_name: "basic-auth-plugin-session"
                              cookie_duration: 34560000000 # max 400 days (400 * 24 * 60 * 60 = 34560000)
                              aes_key: "xxx" # generate with `openssl rand -base64 32`

                          vm_config:
                            runtime: "envoy.wasm.runtime.v8"
                            code:
                              local:
                                filename: "/etc/envoy/proxy-wasm-plugins/basic_auth_plugin.wasm"
                    - name: envoy.filters.http.router
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
      - name: httpbin
        connect_timeout: 5s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: httpbin
          endpoints:
            - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: httpbin-service.basic-auth-plugin.svc.cluster.local
                        port_value: 80
